export const SLIDE_TITLES = {
  0: "Hero",
  1: "Tagline",
  2: "PPIE — 1915 Exposition",
  3: "PPIE — Palace today",
  4: "Coalition handoff",
  5: "Welcome to the Future",
  6: "Vision intro",
  7: "Tour into Tomorrow — intro",
  8: "Tour exhibit 1 — Clean energy",
  9: "Tour exhibit 2",
  10: "Tour exhibit 3",
  11: "Tour exhibit 4",
  12: "Future Lab — intro",
  13: "Future Lab — hands-on",
  14: "Future Lab — scientists",
  15: "Future Lab — learning",
  16: "Heart of it all — intro",
  17: "Food hall — overview",
  18: "Mezzanine dining",
  19: "Dining experience",
  20: "Grounds — intro",
  21: "Grounds — golden hour",
  22: "Grounds — wandering",
  23: "Grounds — wide",
  24: "Evening fountain show",
  25: "Sense of wonder",
  26: "Call to build",
  27: "Letter — sign-off",
};

export const SLIDE_COUNT = 28;
